site            : http://mage2.dev
baseurl 		: http://mage2.dev/index.php/rest/default
consumerkey 	: gbs88be0qtgull72mypfjcoyw2rnokss
consumersecret  : qfpixb280efcbb4tjfwb3w7j7fk0is5d
token 			: sk3pm1gxf3kr7rdinnhbrb4x9h4dmt18
tokensecret 	: 81orpo1k18i9s5k7138h8x01ollpo0nh

